GET http://localhost:3000

###
GET http://localhost:3000/packages

###
GET http://localhost:3000/packages/67fd9369849a22a1025b2a6c

###
GET http://localhost:3000/localhost:3000/packages/67fd9369849a22a1025b2a6c
###
POST http://localhost:3000/staff HTTP/1.1
Content-Type: application/json

{
    "userName":"jdfktu13",
    "password":"njjdjfl134f",
    "firstName":"Jake",
    "lastName":"Blake",
    "email":"jblake@streetlife.com",
    "position":"Marketing Director"
}
